### PR TITLE
Adds glfw requirement

### PR DESCRIPTION
**Pull request by Fohlen**
Hello @helmesjo 
Thanks a lot for making this package, it works like a charm!

I have added the `glfw` requirement in order for it to be able to properly link `GlfwApplication` during `conan install`

### CODE REVIEW

**Comment by helmesjo** [comment]
Thank you @Fohlen !

Quick question: 
Is there any particular reason to opt for `glfw/3.2.1.20180327@bincrafters/stable` instead of just `glfw/3.2.1@bincrafters/stable`? Is the former considered "more stable", or perhaps more recent?

**Comment by Fohlen** [comment]
@helmesjo as far as I can tell not, it was listed as the latest stable on bintray so I used it 👍

**Comment by helmesjo** [comment]
Yeah, can't really find any info regarding this... Anyways, I assume you confirmed this change did the trick so I'll merge as soon as the builds pass! :)

Thanks again!

**Comment by Fohlen** [comment]
@helmesjo apparently there is an error with pip on the older OSX containers but according to https://travis-ci.org/helmesjo/conan-magnum/jobs/500752225 this works fine (and it runs on my mac too). Can you merge anyways? We would like to use this soon 👍

**Comment by helmesjo** [comment]
Not sure I follow, but yes it does appear to be unrelated to this change so I'll merge! :)

**Pull request merged**
